use_frameworks!

target 'ContainerVC_Example' do
  pod 'ContainerVC', :path => '../'

  target 'ContainerVC_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
  end
end
